### ISSUE TITLE
Add "depth=1" when git clone or git module update to save time.

### ISSUE THREAD

**Issue by fangyuanseu** [Nuclei-Software/nuclei-linux-sdk#3]
Hi maintainner,
i met a error message when git module update, may be we can add "depth=1" when update module to resolve this error and sava a lot of time, i'm not sure if take any side effect, please advise, thanks a lot.

**Comment by fanghuaqi** [comment]
Could provide the error message you have met, you can also take a try with this help:

https://stackoverflow.com/questions/2155887/git-submodule-head-reference-is-not-a-tree-error/25875273#25875273

And it you just want to take a try with the source code without any git information, you can use the artifacts built by github ci:

https://github.com/Nuclei-Software/nuclei-linux-sdk/actions/runs/667358598

Thanks
Huaqi

**Comment by fangyuanseu** [comment]
Hi Huaqi,
    Thanks for your quick reply, the error message as below,
''error: RPC failed; HTTP 504 curl 22 The requested URL returned error: 504 Gateway Time-out''
when i added depth=1 could resolve this error, i guess that's because submodule(s) are huge and  with lots of commit history.
and i have another question, i port a coremark and run on ux900 fpga dev kit, which show 2.05 score per MHz, it's it reasonable?

BR
Fang Yuan

**Comment by fangyuanseu** [comment]
Hi Huaqi,
    Thanks for your quick reply, the error message as below,
''error: RPC failed; HTTP 504 curl 22 The requested URL returned error: 504 Gateway Time-out''
when i added depth=1 could resolve this error, i guess that's because submodule(s) are huge and  with lots of commit history.
and i have another question, i port a coremark and run on ux900 fpga dev kit, which show 2.05 score per MHz, it's it reasonable?

BR
Fang Yuan

**Comment by fanghuaqi** [comment]
If you want to evaluate coremark or dhrystone, we prefer to use Nuclei SDK to do this job, the benchmark numbers are published using baremetal benchmark not linux hosted benchmarks.

For `''error: RPC failed; HTTP 504 curl 22 The requested URL returned error: 504 Gateway Time-out''`, it seems to be issue belong to web connection, I can share the repo in zip, just check here 
~~~
link: https://space.dingtalk.com/s/gwHOAsn6FQLOAPWOEAPaACA2NDZmM2U5MDliNzM0OGZjYTAyNWUxMzExYzQ4ODlhOQ 
password: UyDH
~~~

Thanks
Huaqi

**Comment by fanghuaqi** [comment]
closed
